from common import ResourceViewMixin
from applications import ApplicationResourceView, SiteResourceView
from models import ModelListResourceView, ModelDetailResourceView, InlineModelListResourceView, InlineModelDetailResourceView
from storages import StorageListResourceView, StorageDetailResourceView
from auth import AuthenticationResourceView

